import Head from "next/head";
import { Post } from "@/types"; 
import Link from "next/link";
import Styles from '../styles/Home.module.css'


type Props = {
  posts:Post[]
};


export async function getStaticProps() {
  const res= await fetch("http://localhost:3001/api/v1/posts")
  const posts = await res.json();
  
  console.log(posts)
  return {
    props:{
      posts,
    },
    revalidate:60*60*24,
  }
} 

export default function Home({ posts }:Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create-next-app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div className={Styles.homeContainer}>
       <h1>Rails & Next.js Project</h1>
       <Link href="/create-post" className={Styles.createButton}>
           Create New Post
       </Link>

       <div>
        {posts.map((post:Post)=>(
         <div key={post.id} className={Styles.postCard}>
          <Link href={`posts/${post.id}`} className={Styles.PostCardBox}>
            <h2>{post.title}</h2>
          </Link>
            <p>{post.content}</p>
            <button className={Styles.editButton}>Edit</button>
            <button className={Styles.deleteButton}>Delete</button>
         </div> 
        ))}
       </div>
      </div>
    </>
  );
}
